import type { Palette, PixelGrid } from "./pixels";
import { shade } from "./pixels";
import type { ArtPoint, Rect } from "./world";

// Pixel art, one string per row. "." is transparent and "o" is the 1 px outline. Explorer hoods use
// "h" (hood) and "H" (shade), filled in per player by explorerPalette.

export type Facing = "down" | "up" | "left" | "right";
export type SpriteId =
  | "explorer-down"
  | "explorer-up"
  | "explorer-right"
  | "drone"
  | "tower"
  | "chest-closed"
  | "chest-open"
  | "gate"
  | "x-mark"
  | "semicolon"
  | "pine"
  | "tree"
  | "rock"
  | "bush"
  | "snow-rock"
  | "plank";
/** bottom: bottom-centre on the art point; centre: centred on it; hover: centred 12 px above it. */
export type SpriteDef = { w: number; h: number; frames: PixelGrid[]; palette: Palette; anchor: "bottom" | "centre" | "hover" };
export type TextureId = "ice" | "mountains" | "snow" | "forest" | "meadow" | "path" | "bank";

export const OUTLINE = "#0b1020";

export const SPRITES: Record<SpriteId, SpriteDef> = {
  "explorer-down": {
    w: 16,
    h: 16,
    anchor: "bottom",
    palette: { o: "#0b1020", s: "#f1c27d", e: "#0b1020", c: "#334155", C: "#1e293b" },
    frames: [
      [
        "......oooo......",
        ".....ohhhho.....",
        "....ohhhhhho....",
        "...ohhhhhhhho...",
        "...ohhHHHHhho...",
        "..ohhHssssHhho..",
        "..ohHsessesHho..",
        "..ohHssssssHho..",
        "...oHHssssHHo...",
        "..occHHHHHHcco..",
        ".occchhhhhhccco.",
        ".osccccccccccso.",
        "..occcccccccco..",
        "..occCCCCCCcco..",
        "...occoooocco...",
        "....oo....oo....",
      ],
      [
        "......oooo......",
        ".....ohhhho.....",
        "....ohhhhhho....",
        "...ohhhhhhhho...",
        "...ohhHHHHhho...",
        "..ohhHssssHhho..",
        "..ohHsessesHho..",
        "..ohHssssssHho..",
        "...oHHssssHHo...",
        "..occHHHHHHcco..",
        ".occchhhhhhccco.",
        ".osccccccccccso.",
        "..occcccccccco..",
        "..occCCCCCCcco..",
        "...occooooooo...",
        "....oo..........",
      ],
      [
        "......oooo......",
        ".....ohhhho.....",
        "....ohhhhhho....",
        "...ohhhhhhhho...",
        "...ohhHHHHhho...",
        "..ohhHssssHhho..",
        "..ohHsessesHho..",
        "..ohHssssssHho..",
        "...oHHssssHHo...",
        "..occHHHHHHcco..",
        ".occchhhhhhccco.",
        ".osccccccccccso.",
        "..occcccccccco..",
        "..occCCCCCCcco..",
        "...ooooooocco...",
        "..........oo....",
      ],
    ],
  },
  "explorer-up": {
    w: 16,
    h: 16,
    anchor: "bottom",
    palette: { o: "#0b1020", s: "#f1c27d", e: "#0b1020", c: "#334155", C: "#1e293b" },
    frames: [
      [
        "......oooo......",
        ".....ohhhho.....",
        "....ohhhhhho....",
        "...ohhhhhhhho...",
        "...ohhhhhhhho...",
        "..ohhhhhhhhhho..",
        "..ohhHHHHHHhho..",
        "..ohHHHHHHHHho..",
        "...oHHHHHHHHo...",
        "..occHHHHHHcco..",
        ".occcchhhhcccco.",
        ".osccccccccccso.",
        "..occcccccccco..",
        "..occCCCCCCcco..",
        "...occoooocco...",
        "....oo....oo....",
      ],
      [
        "......oooo......",
        ".....ohhhho.....",
        "....ohhhhhho....",
        "...ohhhhhhhho...",
        "...ohhhhhhhho...",
        "..ohhhhhhhhhho..",
        "..ohhHHHHHHhho..",
        "..ohHHHHHHHHho..",
        "...oHHHHHHHHo...",
        "..occHHHHHHcco..",
        ".occcchhhhcccco.",
        ".osccccccccccso.",
        "..occcccccccco..",
        "..occCCCCCCcco..",
        "...occooooooo...",
        "....oo..........",
      ],
      [
        "......oooo......",
        ".....ohhhho.....",
        "....ohhhhhho....",
        "...ohhhhhhhho...",
        "...ohhhhhhhho...",
        "..ohhhhhhhhhho..",
        "..ohhHHHHHHhho..",
        "..ohHHHHHHHHho..",
        "...oHHHHHHHHo...",
        "..occHHHHHHcco..",
        ".occcchhhhcccco.",
        ".osccccccccccso.",
        "..occcccccccco..",
        "..occCCCCCCcco..",
        "...ooooooocco...",
        "..........oo....",
      ],
    ],
  },
  "explorer-right": {
    w: 16,
    h: 16,
    anchor: "bottom",
    palette: { o: "#0b1020", s: "#f1c27d", e: "#0b1020", c: "#334155", C: "#1e293b" },
    frames: [
      [
        "......oooo......",
        ".....ohhhho.....",
        "....ohhhhhho....",
        "...ohhhhhhhho...",
        "...ohhhhhHHho...",
        "..ohhhhHsssso...",
        "..ohhhhHsseso...",
        "..ohhhhHsssso...",
        "...ohhHHssso....",
        "...ocHHHHccoo...",
        "..occchhhcccco..",
        "..occccccccso...",
        "...occcccccco...",
        "...occCCCCcco...",
        "....occoocco....",
        ".....oo..oo.....",
      ],
      [
        "......oooo......",
        ".....ohhhho.....",
        "....ohhhhhho....",
        "...ohhhhhhhho...",
        "...ohhhhhHHho...",
        "..ohhhhHsssso...",
        "..ohhhhHsseso...",
        "..ohhhhHsssso...",
        "...ohhHHssso....",
        "...ocHHHHccoo...",
        "..occchhhcccco..",
        "..occccccccso...",
        "...occcccccco...",
        "...occCCCCcco...",
        "...occoooocco...",
        "....oo....oo....",
      ],
      [
        "......oooo......",
        ".....ohhhho.....",
        "....ohhhhhho....",
        "...ohhhhhhhho...",
        "...ohhhhhHHho...",
        "..ohhhhHsssso...",
        "..ohhhhHsseso...",
        "..ohhhhHsssso...",
        "...ohhHHssso....",
        "...ocHHHHccoo...",
        "..occchhhcccco..",
        "..occccccccso...",
        "...occcccccco...",
        "...occCCCCcco...",
        "....ooccccoo....",
        "......oooo......",
      ],
    ],
  },
  drone: {
    w: 12,
    h: 12,
    anchor: "hover",
    palette: { o: "#0b1020", p: "#cbd5e1", m: "#64748b", b: "#38bdf8", l: "#e0f2fe", k: "#0b1020" },
    frames: [
      [
        ".oooo..oooo.",
        "oppppooppppo",
        ".ommoooommo.",
        "..ooommooo..",
        "...obbbbo...",
        "..obbbbbbo..",
        ".obbllllbbo.",
        ".obblkklbbo.",
        ".obbllllbbo.",
        "..obbbbbbo..",
        "...oboobo...",
        "....o..o....",
      ],
      [
        "...oo..oo...",
        "..oppooppo..",
        ".ommoooommo.",
        "..ooommooo..",
        "...obbbbo...",
        "..obbbbbbo..",
        ".obbllllbbo.",
        ".obblkklbbo.",
        ".obbllllbbo.",
        "..obbbbbbo..",
        "...oboobo...",
        "....o..o....",
      ],
    ],
  },
  tower: {
    w: 16,
    h: 32,
    anchor: "bottom",
    palette: { m: "#94a3b8", M: "#475569", L: "#1e293b", k: "#64748b", K: "#334155" },
    frames: [
      [
        "................",
        "......MMMM......",
        "......MLLM......",
        "......MMMM......",
        ".......mm.......",
        ".......mm.......",
        "......mMMm......",
        "......m..m......",
        "......mmmm......",
        "......m..m......",
        ".....mMmmMm.....",
        ".....m....m.....",
        ".....mmmmmm.....",
        ".....m.mm.m.....",
        "....mMm..mMm....",
        "....m......m....",
        "....mmmmmmmm....",
        "....m.m..m.m....",
        "...mMm....mMm...",
        "...m........m...",
        "...mmmmmmmmmm...",
        "...m.m....m.m...",
        "..mMm......mMm..",
        "..m..........m..",
        "..mmmmmmmmmmmm..",
        "..m.m......m.m..",
        ".mMm........mMm.",
        ".m............m.",
        ".kkkkkkkkkkkkkk.",
        ".kKkkkkkkkkkkKk.",
        ".KKKKKKKKKKKKKK.",
        "................",
      ],
    ],
  },
  "chest-closed": {
    w: 16,
    h: 16,
    anchor: "bottom",
    palette: { o: "#0b1020", w: "#7c4a1e", W: "#9a5f2b", y: "#f59e0b", Y: "#fbbf24", d: "#1c1917" },
    frames: [
      [
        "................",
        "................",
        "................",
        "...oooooooooo...",
        "..owwwwwwwwwwo..",
        ".owWWWWWWWWWWwo.",
        ".owWyyyyyyyyWwo.",
        ".owwwwwwwwwwwwo.",
        ".owwwwwYYwwwwwo.",
        ".owWWWWYYWWWWwo.",
        ".owWWWWWWWWWWwo.",
        ".owyWWWWWWWWywo.",
        ".owWWWWWWWWWWwo.",
        ".owwwwwwwwwwwwo.",
        "..oooooooooooo..",
        "................",
      ],
    ],
  },
  "chest-open": {
    w: 16,
    h: 16,
    anchor: "bottom",
    palette: { o: "#0b1020", w: "#7c4a1e", W: "#9a5f2b", y: "#f59e0b", Y: "#fbbf24", d: "#1c1917" },
    frames: [
      [
        "...oooooooooo...",
        "..owwwwwwwwwwo..",
        ".owWWWWWWWWWWwo.",
        ".owWyyyyyyyyWwo.",
        ".owwwwwwwwwwwwo.",
        ".owddddddddddwo.",
        ".owddddddddddwo.",
        ".owwwwwwwwwwwwo.",
        ".owwwwwYYwwwwwo.",
        ".owWWWWYYWWWWwo.",
        ".owWWWWWWWWWWwo.",
        ".owyWWWWWWWWywo.",
        ".owWWWWWWWWWWwo.",
        ".owwwwwwwwwwwwo.",
        "..oooooooooooo..",
        "................",
      ],
    ],
  },
  gate: {
    w: 32,
    h: 16,
    anchor: "bottom",
    palette: { S: "#475569", s: "#94a3b8", t: "#1e293b", g: "#22c55e", G: "#4ade80", K: "#334155" },
    frames: [
      [
        "................................",
        ".SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.",
        ".SssssssssssssssssssssssssssssS.",
        ".SsSSSSSSSSSSSSSSSSSSSSSSSSSSsS.",
        ".SssS....................SssssS.",
        ".SssS....................SttttS.",
        ".SssS....................StgGtS.",
        ".SsSS....................StggtS.",
        ".SssS....................SttttS.",
        ".SssS....................SssssS.",
        ".SsSS....................SSsssS.",
        ".SssS....................SssssS.",
        ".SssS....................SssssS.",
        ".SSSS....................SSSSSS.",
        ".KKKK....................KKKKKK.",
        "................................",
      ],
    ],
  },
  "x-mark": {
    w: 8,
    h: 8,
    anchor: "centre",
    palette: { o: "#0b1020", r: "#dc2626" },
    frames: [
      [
        ".oo..oo.",
        "orroorro",
        ".orrrro.",
        "..orro..",
        ".orrrro.",
        "orroorro",
        ".oo..oo.",
        "........",
      ],
    ],
  },
  semicolon: {
    w: 8,
    h: 12,
    anchor: "bottom",
    palette: { o: "#0b1020", y: "#f59e0b", Y: "#fde68a" },
    frames: [
      [
        "...oo...",
        "..oyyo..",
        ".oyYYyo.",
        ".oyYYyo.",
        "..oyyo..",
        "...oo...",
        "..oyyo..",
        ".oyYYyo.",
        ".oyYYyo.",
        "..oyyo..",
        ".oyyo...",
        "..oo....",
      ],
    ],
  },
  pine: {
    w: 16,
    h: 20,
    anchor: "bottom",
    palette: { o: "#0b1020", n: "#f1f5f9", N: "#ffffff", g: "#166534", G: "#14532d", t: "#6b4423", T: "#4a2f18" },
    frames: [
      [
        ".......oo.......",
        "......onno......",
        ".....onNNno.....",
        "....onNNNNno....",
        ".....oggggo.....",
        "....ogGggGgo....",
        "...ogGGggGGgo...",
        "....onnnnnno....",
        "...oggggggggo...",
        "..ogGggggggGgo..",
        ".ogGGGggggGGGgo.",
        "..onnnnnnnnnno..",
        "..oggggggggggo..",
        ".ogGggggggggggo.",
        "ogGGgggggggggGgo",
        ".onnnnnnnnnnnno.",
        "..oooottttoooo..",
        ".....otTTto.....",
        ".....otttto.....",
        "......oooo......",
      ],
    ],
  },
  tree: {
    w: 16,
    h: 18,
    anchor: "bottom",
    palette: { o: "#0b1020", g: "#1f7a3a", G: "#14532d", L: "#2f9e4f", t: "#6b4423", T: "#4a2f18" },
    frames: [
      [
        ".....oooooo.....",
        "....oggggggo....",
        "...ogGggggGgo...",
        "..ogGggLLggGgo..",
        ".ogGgLLLLgggggo.",
        ".oggLLLgggggggo.",
        "ogggggggggggGggo",
        "ogGgggggggggGGgo",
        "ogGGgggggggGGggo",
        ".ogGGgggggGGggo.",
        ".oggGGGGGGGgggo.",
        "..ogggggggggggo.",
        "...oggggggggoo..",
        "....oottttoo....",
        ".....otTTto.....",
        ".....otttto.....",
        "....otttttto....",
        ".....oooooo.....",
      ],
    ],
  },
  rock: {
    w: 16,
    h: 16,
    anchor: "bottom",
    palette: { o: "#0b1020", r: "#64748b", R: "#94a3b8", D: "#475569" },
    frames: [
      [
        "................",
        "................",
        "................",
        "................",
        "......oooo......",
        "....oorrrroo....",
        "...orrRRRRrro...",
        "..orRRRrrrRRro..",
        ".orRRrrrrrrRRro.",
        ".orRrrrrrrrrRro.",
        ".orrrrrrrrrrDro.",
        ".orrrrrrrrrDDro.",
        "..orrrrrrDDDro..",
        "...orrrrrrrro...",
        "....oooooooo....",
        "................",
      ],
    ],
  },
  bush: {
    w: 16,
    h: 16,
    anchor: "bottom",
    palette: { o: "#0b1020", g: "#2f7d3a", G: "#1e5a2a", L: "#4caf50" },
    frames: [
      [
        "................",
        "................",
        "................",
        "................",
        "................",
        ".....oo..oo.....",
        "....oggooggo....",
        "...ogLLggLLgo...",
        "..ogLLggggLLgo..",
        ".oggLgggggggggo.",
        ".ogggggggggGggo.",
        ".oggggggggGGggo.",
        "..ogggggGGGggo..",
        "...oggggggggo...",
        "....oooooooo....",
        "................",
      ],
    ],
  },
  "snow-rock": {
    w: 16,
    h: 16,
    anchor: "bottom",
    palette: { o: "#0b1020", r: "#64748b", R: "#94a3b8", D: "#475569", n: "#e2e8f0", N: "#ffffff" },
    frames: [
      [
        "................",
        "................",
        "................",
        "................",
        "......oooo......",
        "....oonnnnoo....",
        "...onnNNNNnno...",
        "..onNNNnnnNNno..",
        ".ornnnnnnnnnnro.",
        ".orRrrrrrrrrRro.",
        ".orrrrrrrrrrDro.",
        ".orrrrrrrrrDDro.",
        "..orrrrrrDDDro..",
        "...orrrrrrrro...",
        "....oooooooo....",
        "................",
      ],
    ],
  },
  plank: {
    w: 26,
    h: 3,
    anchor: "bottom",
    palette: { p: "#4a2f18", w: "#b07a45", W: "#8f5f33", d: "#3a2412" },
    frames: [
      [
        "pwwwwwwwwwwwwwwwwwwwwwwwwp",
        "pWWWWWWWWWWWWWWWWWWWWWWWWp",
        "pddddddddddddddddddddddddp",
      ],
    ],
  },
};

export const TEXTURES: Record<TextureId, { grid: PixelGrid; palette: Palette }> = {
  meadow: {
    palette: { g: "#3f7d3a", l: "#4f9a45", d: "#356b31" },
    grid: [
      "gggldgggggggglgg",
      "gggggggggggggdgg",
      "gggdglgglggggggg",
      "glggglgggglggdgg",
      "dggggggggdgggggg",
      "lggggdgggggggggg",
      "gggdggggggdggggl",
      "gggggglggggggggg",
      "gddggggggggggggg",
      "ggggglgdggggglgd",
      "gglgggggggggggdd",
      "ggggggggdggggggg",
      "dgdllgglgggldggg",
      "gggggggggggggggg",
      "ggggggggggglgggg",
      "gggggglgggggglgl",
    ],
  },
  forest: {
    palette: { f: "#24452a", l: "#2d5634", d: "#1b3520" },
    grid: [
      "ffffffdfflffffff",
      "flffffflffffffff",
      "fffffffffffffffl",
      "dlfffffdlfffffff",
      "fffffffffdfdfdff",
      "fffdfffffllflffd",
      "ffdlfffffffffflf",
      "ffffffdffflfdfdf",
      "ffffffffffffffff",
      "dffffffffffffflf",
      "fffffdfffffdlffd",
      "fdffffffflffffff",
      "dffflffffffffffl",
      "dfdffffdffffdfff",
      "fffdlffffldfdflf",
      "fflfdflfffffdddf",
    ],
  },
  snow: {
    palette: { n: "#e2e8f0", w: "#f8fafc", s: "#cbd5e1" },
    grid: [
      "nnnwsnnsnnnsnnnn",
      "nssnwwnwwnnnwswn",
      "nnnnnnnwnnnnwnnn",
      "nwnnnnnwnwwnnnns",
      "snnnnnwnnwnsnnsn",
      "nnnnnnwnnnnnnnnn",
      "nnnnnnwnsnnnnnnw",
      "nnswnnnnnnnnnnnn",
      "nnnswnnnnwnnnnnn",
      "nnnnnwnsnnnnnnnn",
      "nnwnnnwnsnnwnswn",
      "nwnwnnnnnnnnwnnn",
      "nnnnnnwnnnnsnsnn",
      "nnnnnnnnnnnnnnnw",
      "nnnnnnnnnnnsnnwn",
      "nnnsnnwnnnnnnnnn",
    ],
  },
  ice: {
    palette: { i: "#7cc4e8", l: "#b9e3f5", c: "#4f9cc7" },
    grid: [
      "iiiiiiiiiiiiiiii",
      "iilliiiiiiiiiiii",
      "iiilliiiiiiciiii",
      "iiiiiiiiiiciiiii",
      "iiiiiiiiicciiiii",
      "iiiiiiiiciiiilli",
      "iiiiiiiiciiiiill",
      "iiiiiiicciiiiiii",
      "iiliiiiiiciiiiii",
      "illiiiiiiicciiii",
      "iiiiiiiiiiiciiii",
      "iiiiiiiiiiiiiiii",
      "iiiiiillliiiiiii",
      "iiiiiiiilliiiiii",
      "iiiiiiiiiiiiiiil",
      "iiiiiiiiiiiiiill",
    ],
  },
  mountains: {
    palette: { r: "#64748b", l: "#7c8ba1", d: "#475569" },
    grid: [
      "rrrrrrlrrrrrrrrd",
      "rrlrrlrrdrrrrrrr",
      "rrrrrlrdrrrrldrr",
      "rrrrrrrrdrrrrrrr",
      "rrrrrlrrlrrdrlrl",
      "rrrrrrrlrlddrrrl",
      "rldrrrrrrrrlrrrr",
      "rrrlrrdrlldrdllr",
      "lrrrdrrrrrrrrrrr",
      "rrrrrrrrrrrrdrrr",
      "drrlrrlrrrrrldld",
      "rlrrdrrrrrrlrdrr",
      "lrlrrlrrddldrrdr",
      "lrdrrrrdrrlrdrrd",
      "rrrrrrlrrddrrrdr",
      "rrrdrrrrrrrlrdrd",
    ],
  },
  path: {
    palette: { p: "#8b6b46", l: "#9c7a50", d: "#735738" },
    grid: [
      "pdpppplpppplpppp",
      "ppdlppppplppplpp",
      "pppppdpldppppppp",
      "pdpppppppppppppp",
      "lppplpllplpppppp",
      "pppdppppldlppppp",
      "pddppppppppdpppp",
      "lplpppppddlppppp",
      "pdppplppppppdplp",
      "pdppppppppppdppp",
      "pplpdppppppllppp",
      "pdppplpppdppplpl",
      "ppplppdppldldplp",
      "lplpppplpppppppp",
      "pppplpdpppppplpp",
      "ppppppdppplppdpp",
    ],
  },
  bank: {
    palette: { b: "#3b5b73" },
    grid: [
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
      "bbbbbbbbbbbbbbbb",
    ],
  },
};

/** A player's explorer colours: the hood in their colour with a darker shade. */
export const explorerPalette = (hood: string): Palette => ({ ...SPRITES["explorer-down"].palette, h: hood, H: shade(hood, -0.3) });

/** The art pixels a sprite covers when placed on an art point (see SpriteDef.anchor). */
export function spriteBox(id: SpriteId, at: ArtPoint): Rect {
  const { w, h, anchor } = SPRITES[id];
  const x = at.x - Math.floor(w / 2);
  if (anchor === "bottom") return { x, y: at.y - h + 1, w, h };
  const cy = anchor === "hover" ? at.y - 12 : at.y;
  return { x, y: cy - Math.floor(h / 2), w, h };
}

/** Light sources, in absolute art pixels: the tower's lamp and the gate's terminal cursor. */
export const LIGHTS: { towerLamp: ArtPoint; gateTerminal: ArtPoint } = {
  towerLamp: { x: 45, y: 3 },
  gateTerminal: { x: 172, y: 81 },
};
