import type { ChestQuestion } from "../types";

export const CPP1_BANK: readonly ChestQuestion[] = [
  {
    kind: "blank",
    id: "cpp-cout",
    lang: "cpp",
    prompt: "Print Hello to standard output (the normal output, not the error stream).",
    code: ["#include <iostream>", "int main() {", '  std::___ << "Hello";', "}"],
    answers: ["cout", "wcout"],
    caseSensitive: true,
    // The complete set of standard stream objects.
    live: {
      kind: "legal",
      tokens: ["cout", "cin", "cerr", "clog", "wcout", "wcin", "wcerr", "wclog"],
      label: "a standard stream object",
    },
    blocks: ["cout", "cin", "cerr", "print", "console"],
    hint: "It's the 'character output' stream.",
    explain:
      "std::cout is the standard output stream; << sends text into it. std::cerr and std::clog reach the screen too, but they are the error and log streams. std::wcout is cout's wide-character twin.",
  },
  {
    kind: "choice",
    id: "cpp-semicolon",
    lang: "cpp",
    prompt: "What ends almost every statement in C++?",
    options: [";", ".", ":", "nothing"],
    correct: 0,
    codeOptions: true,
    hint: "Devlandia's lost artifact is one of these.",
    explain: "A semicolon ends a C++ statement, the very thing the Golden Semicolon stands for.",
  },
  {
    kind: "choice",
    id: "cpp-int-div",
    lang: "cpp",
    prompt: "What does this print?",
    code: ["int a = 7 / 2;", "std::cout << a;"],
    options: ["3", "3.5", "4", "2"],
    correct: 0,
    codeOptions: true,
    hint: "Both numbers are whole numbers.",
    explain: "Dividing two ints drops the remainder, so 7 / 2 is 3.",
  },
  {
    kind: "blank",
    id: "cpp-include",
    lang: "cpp",
    prompt: "Bring in the library that provides std::cout.",
    code: ["#___ <iostream>", "int main() {", '  std::cout << "Hi";', "}"],
    answers: ["include"],
    caseSensitive: true,
    // Every standard preprocessor directive name.
    live: {
      kind: "legal",
      tokens: ["include", "define", "undef", "if", "ifdef", "ifndef", "elif", "elifdef", "elifndef", "else", "endif", "line", "error", "pragma", "warning", "embed"],
      label: "a preprocessor directive",
    },
    blocks: ["include", "define", "pragma", "using", "namespace"],
    hint: "Think of putting another file's contents into yours.",
    explain: "#include copies a header into your file. #define makes a macro and #pragma gives the compiler a special instruction. using and namespace are not preprocessor directives.",
  },
  {
    kind: "choice",
    id: "cpp-main",
    lang: "cpp",
    prompt: "Which function does every C++ program start running at?",
    options: ["main", "start", "run", "init"],
    correct: 0,
    codeOptions: true,
    hint: "Its name means 'principal'.",
    explain: "Execution begins at main(). start, run and init are ordinary names with no special meaning.",
  },
  {
    kind: "choice",
    id: "cpp-bool-print",
    lang: "cpp",
    prompt: "What does this print?",
    code: ["std::cout << (5 > 3);"],
    options: ["1", "true", "5", "0"],
    correct: 0,
    codeOptions: true,
    hint: "Booleans print as numbers unless you ask otherwise.",
    explain: "5 > 3 is true, and cout prints a true bool as 1 (and false as 0) unless boolalpha is set.",
  },
];

export const CPP2_BANK: readonly ChestQuestion[] = [
  {
    kind: "blank",
    id: "cpp-for",
    lang: "cpp",
    prompt: "Make the loop print 012.",
    code: ["for (int i = 0; i ___ 3; i++) {", "  std::cout << i;", "}"],
    answers: ["<", "!=", "not_eq"],
    caseSensitive: true,
    // The three-way <=> is a category of its own, so it is truthfully not one.
    live: {
      kind: "legal",
      tokens: ["<", "<=", ">", ">=", "==", "!=", "not_eq"],
      label: "a relational or equality operator",
    },
    blocks: ["<", "<=", ">", "=>", "=<"],
    hint: "The loop must stop before i reaches 3.",
    explain:
      "i < 3 runs for 0, 1 and 2. i != 3 (also spelled not_eq) does too, but < is the usual choice because it still stops if i ever jumps past 3. => and =< aren't C++ operators.",
  },
  {
    kind: "choice",
    id: "cpp-address",
    lang: "cpp",
    prompt: "Which expression gives the address of a variable x?",
    options: ["&x", "*x", "#x", "@x"],
    correct: 0,
    codeOptions: true,
    hint: "The 'and' sign.",
    explain: "&x is the address of x; *p reads what a pointer p points to.",
  },
  {
    kind: "choice",
    id: "cpp-ref",
    lang: "cpp",
    prompt: "What does this print?",
    code: ["int n = 5;", "int& r = n;", "r = 9;", "std::cout << n;"],
    options: ["9", "5", "14", "Error"],
    correct: 0,
    codeOptions: true,
    hint: "r is another name for n.",
    explain: "A reference is an alias: changing r changes n.",
  },
  {
    kind: "blank",
    id: "cpp-while",
    lang: "cpp",
    prompt: "Keep counting while n is below 3.",
    code: ["int n = 0;", "___ (n < 3) {", "  std::cout << n;", "  n++;", "}"],
    answers: ["while"],
    caseSensitive: true,
    live: { kind: "notLegal", tokens: ["until", "loop", "repeat", "whilst", "foreach"], label: "a C++ keyword" },
    blocks: ["while", "for", "if", "until", "do"],
    hint: "It is the loop that checks its condition before every pass.",
    explain: "while repeats its block as long as the condition is true. if runs it at most once, and do … while checks the condition after the first pass.",
  },
  {
    kind: "choice",
    id: "cpp-array-index",
    lang: "cpp",
    prompt: "What does this print?",
    code: ["int a[3] = {10, 20, 30};", "std::cout << a[1];"],
    options: ["20", "10", "30", "1"],
    correct: 0,
    codeOptions: true,
    hint: "Array indexes start at 0.",
    explain: "a[0] is 10, so a[1] is the second element: 20.",
  },
  {
    kind: "choice",
    id: "cpp-deref",
    lang: "cpp",
    prompt: "What does this print?",
    code: ["int n = 8;", "int* p = &n;", "std::cout << *p;"],
    options: ["8", "The address of n", "p", "*p"],
    correct: 0,
    codeOptions: true,
    hint: "*p follows the pointer.",
    explain: "*p reads the value p points to, which is n's 8. Printing p itself would show an address.",
  },
];
