import type { ChestQuestion } from "../types";

export const HTML_BANK: readonly ChestQuestion[] = [
  {
    kind: "blank",
    id: "html-link",
    lang: "html",
    prompt: "Make the link go to the Devlandia site.",
    code: ['<a ___="https://devlandia.dev">Home</a>'],
    answers: ["href"],
    caseSensitive: false,
    live: { kind: "notLegal", tokens: ["url", "ref", "goto", "hyperlink"], label: "an HTML attribute" },
    blocks: ["href", "src", "link", "url", "alt"],
    hint: "The attribute's name is short for 'hypertext reference'.",
    explain: "href sets where a link goes. src is for images and scripts.",
  },
  {
    kind: "choice",
    id: "html-heading",
    lang: "html",
    prompt: "Which tag makes the largest heading?",
    options: ["<h1>", "<h6>", "<head>", "<header>"],
    correct: 0,
    codeOptions: true,
    hint: "Headings run from 1 (biggest) to 6 (smallest).",
    explain: "<h1> is the top heading and <h6> the smallest. <head> holds page metadata, and <header> is a page section.",
  },
  {
    kind: "blank",
    id: "html-list",
    lang: "html",
    prompt: "Finish the list item.",
    code: ["<ul>", "  <___>Apples</li>", "</ul>"],
    answers: ["li"],
    caseSensitive: false,
    live: { kind: "notLegal", tokens: ["item", "list", "bullet", "listitem"], label: "an HTML tag" },
    blocks: ["li", "ol", "item", "p"],
    hint: "The opening tag must match the closing tag.",
    explain: "Each item in a list sits in an <li> (list item) element.",
  },
  {
    kind: "blank",
    id: "html-img-alt",
    lang: "html",
    prompt: "Describe the picture for screen readers.",
    code: ['<img src="cat.png" ___="A sleeping cat">'],
    answers: ["alt"],
    caseSensitive: false,
    live: { kind: "notLegal", tokens: ["text", "description", "desc", "caption", "label"], label: "an HTML attribute" },
    blocks: ["alt", "title", "src", "caption", "id"],
    hint: "It is short for 'alternative text'.",
    explain: "alt gives a picture its text for screen readers and for when it can't load. title only adds a tooltip, and src is where the picture comes from.",
  },
  {
    kind: "choice",
    id: "html-table-row",
    lang: "html",
    prompt: "Which tag starts a row in an HTML table?",
    options: ["<tr>", "<td>", "<th>", "<row>"],
    correct: 0,
    codeOptions: true,
    hint: "Think 'table row'.",
    explain: "<tr> is a table row. <td> is a cell inside a row and <th> a header cell. There is no <row> tag.",
  },
  {
    kind: "choice",
    id: "html-input-type",
    lang: "html",
    prompt: "Which input type hides what the user types, showing dots instead?",
    options: ['type="password"', 'type="hidden"', 'type="secret"', 'type="text"'],
    correct: 0,
    codeOptions: true,
    hint: "Think of what you type to log in.",
    explain: 'type="password" masks the characters as they are typed. type="hidden" is a field the user never sees, type="text" shows what is typed, and "secret" is not a type.',
  },
];
