import type { ChestQuestion } from "../types";

/** Every public method name of java.io.PrintStream in Java 21, inherited ones included. */
const PRINT_STREAM =
  "append charset checkError close equals flush format getClass hashCode notify notifyAll nullOutputStream print printf println toString wait write writeBytes";

export const JAVA_BANK: readonly ChestQuestion[] = [
  {
    kind: "blank",
    id: "java-println",
    lang: "java",
    prompt: "Print Hello on its own line.",
    code: ['System.out.___("Hello");'],
    answers: ["println"],
    caseSensitive: true,
    live: { kind: "legal", tokens: PRINT_STREAM.split(" "), label: "a System.out method" },
    blocks: ["println", "print", "printf", "log", "echo"],
    hint: "The method's name ends with 'ln', for line.",
    explain: "println prints and ends the line; print and printf don't end it. log and echo aren't System.out methods.",
  },
  {
    kind: "choice",
    id: "java-int",
    lang: "java",
    prompt: "Which type holds whole numbers like 42?",
    options: ["int", "String", "boolean", "double"],
    correct: 0,
    codeOptions: true,
    hint: "Short for 'integer'.",
    explain: "int stores whole numbers; double stores decimals and String stores text.",
  },
  {
    kind: "choice",
    id: "java-plus-eq",
    lang: "java",
    prompt: "What does this print?",
    code: ["int x = 10;", "x += 5;", "System.out.println(x);"],
    options: ["15", "105", "10", "5"],
    correct: 0,
    codeOptions: true,
    hint: "x += 5 means x = x + 5.",
    explain: "+= adds to the variable, so x becomes 15.",
  },
  {
    kind: "blank",
    id: "java-class",
    lang: "java",
    prompt: "Declare a class named Game.",
    code: ["public ___ Game {", "}"],
    answers: ["class"],
    caseSensitive: true,
    live: { kind: "notLegal", tokens: ["def", "object", "struct", "function", "klass"], label: "a Java keyword" },
    blocks: ["class", "interface", "enum", "def", "void"],
    hint: "It is the keyword for the blueprint that objects are made from.",
    explain: "class declares a class. interface and enum declare other kinds of types, def belongs to Python and void is a method's return type.",
  },
  {
    kind: "choice",
    id: "java-equals",
    lang: "java",
    prompt: "How do you check that two Strings, a and b, hold the same text?",
    options: ["a.equals(b)", "a = b", "a === b", "a.same(b)"],
    correct: 0,
    codeOptions: true,
    hint: "It is a method, not an operator.",
    explain: "equals compares the text. = assigns, === does not exist in Java, and same is not a String method. (== asks whether both variables point to the same object, which can give the wrong answer for Strings.)",
  },
  {
    kind: "choice",
    id: "java-array-len",
    lang: "java",
    prompt: "What does this print?",
    code: ["int[] arr = {4, 5, 6};", "System.out.println(arr.length);"],
    options: ["3", "2", "6", "15"],
    correct: 0,
    codeOptions: true,
    hint: "length counts the elements.",
    explain: "arr.length is how many elements the array holds: three. It is not their sum and not the last value.",
  },
];
