import type { ChestQuestion } from "../types";

export const JS_BANK: readonly ChestQuestion[] = [
  {
    kind: "blank",
    id: "js-console-log",
    lang: "javascript",
    prompt: "Print Hello to the console with its everyday, general-purpose method (not one of the special warning or error ones).",
    code: ['console.___("Hello");'],
    answers: ["log"],
    caseSensitive: true,
    // Every method on the console object in Node 22 and current browsers.
    live: {
      kind: "legal",
      tokens: [
        "assert", "clear", "count", "countReset", "debug", "dir", "dirxml", "error", "group", "groupCollapsed", "groupEnd",
        "info", "log", "profile", "profileEnd", "table", "time", "timeEnd", "timeLog", "timeStamp", "trace", "warn",
      ],
      label: "a method of the console object",
    },
    blocks: ["log", "warn", "error", "print", "echo"],
    hint: "It shares its name with a ship's diary.",
    explain: "console.log writes a message to the console. warn and error also print, but they mark the message as a warning or an error; print and echo are not console methods.",
  },
  {
    kind: "blank",
    id: "js-const",
    lang: "javascript",
    prompt: "Declare name so that it can never be reassigned.",
    code: ['___ name = "Ada";'],
    answers: ["const"],
    caseSensitive: true,
    live: { kind: "legal", tokens: ["var", "let", "const"], label: "a JavaScript declaration keyword" },
    blocks: ["const", "let", "var", "function", "int"],
    hint: "It is short for constant.",
    explain: "const creates a binding that cannot be reassigned. let and var both allow reassignment, and function and int do not declare a variable here.",
  },
  {
    kind: "choice",
    id: "js-strict-equal",
    lang: "javascript",
    prompt: "What does this evaluate to?",
    code: ['5 === "5"'],
    options: ["false", "true", "5", "Error"],
    correct: 0,
    codeOptions: true,
    hint: "=== also compares the types.",
    explain: 'The strict equality operator === does no type conversion, so the number 5 and the string "5" are not equal.',
  },
  {
    kind: "choice",
    id: "js-array-length",
    lang: "javascript",
    prompt: "What does this evaluate to?",
    code: ["[4, 5, 6].length"],
    options: ["3", "2", "6", "undefined"],
    correct: 0,
    codeOptions: true,
    hint: "Count the items, not their values.",
    explain: "An array's length is how many items it holds. This array has three.",
  },
  {
    kind: "choice",
    id: "js-template",
    lang: "javascript",
    prompt: "What does this print?",
    code: ['const name = "Ada";', "console.log(`Hi ${name}`);"],
    options: ["Hi Ada", "Hi ${name}", "Hi name", "undefined"],
    correct: 0,
    codeOptions: true,
    hint: "Backticks let ${...} insert a value.",
    explain: "Inside a template literal, ${name} is replaced by the value of name, so it prints Hi Ada.",
  },
  {
    kind: "choice",
    id: "js-typeof",
    lang: "javascript",
    prompt: "What does this evaluate to?",
    code: ["typeof 42"],
    options: ['"number"', '"integer"', '"int"', '"digit"'],
    correct: 0,
    codeOptions: true,
    hint: "JavaScript has one type for all its numbers.",
    explain: 'typeof gives the name of the value\'s type as a string. All numbers, whole or not, are of type "number".',
  },
];
