import type { ChestQuestion } from "../types";

export const PHP_BANK: readonly ChestQuestion[] = [
  {
    kind: "blank",
    id: "php-echo",
    lang: "php",
    prompt: "Print the greeting.",
    code: ["<?php", '  ___ "Hello, Devlandia!";', "?>"],
    answers: ["echo", "print"],
    caseSensitive: false,
    // Exactly the reserved words that parse in this line.
    live: {
      kind: "legal",
      tokens: ["echo", "print", "return", "include", "include_once", "require", "require_once", "throw", "clone"],
      label: "a PHP keyword that can take a string here",
    },
    blocks: ["echo", "return", "include", "console.log", "printf"],
    hint: "PHP's usual output statement echoes what you give it.",
    explain: "echo (or print) sends text to the page. console.log is JavaScript, and printf is a function that needs brackets.",
  },
  {
    kind: "choice",
    id: "php-var",
    lang: "php",
    prompt: "What symbol comes before every PHP variable's name?",
    options: ["$", "@", "#", "&"],
    correct: 0,
    codeOptions: true,
    hint: "It's a currency symbol.",
    explain: "PHP variables are written with a $ before the name, as in $name.",
  },
  {
    kind: "choice",
    id: "php-concat",
    lang: "php",
    prompt: "What does this print?",
    code: ['<?php $a = 5; $b = "5"; echo $a . $b; ?>'],
    options: ["55", "10", "5 5", "Error"],
    correct: 0,
    codeOptions: true,
    hint: "In PHP the dot joins strings; it doesn't add.",
    explain: 'The . operator concatenates, so 5 and "5" become "55".',
  },
  {
    kind: "blank",
    id: "php-if",
    lang: "php",
    prompt: "Run the greeting only for adults.",
    code: ["$age = 20;", "___ ($age >= 18) {", '  echo "Welcome";', "}"],
    answers: ["if"],
    caseSensitive: false,
    live: { kind: "notLegal", tokens: ["when", "whenever", "check", "unless", "iff"], label: "a PHP keyword" },
    blocks: ["if", "else", "elseif", "when", "for"],
    hint: "It is the two-letter keyword that starts a condition.",
    explain: "if runs its block only when the condition is true. else and elseif only work after an if.",
  },
  {
    kind: "choice",
    id: "php-array",
    lang: "php",
    prompt: "Which line creates an array of three numbers?",
    options: ["$nums = [1, 2, 3];", "$nums = (1, 2, 3);", "$nums = {1, 2, 3};", "$nums = <1, 2, 3>;"],
    correct: 0,
    codeOptions: true,
    hint: "PHP arrays are written with square brackets.",
    explain: "[1, 2, 3] is an array literal. Round brackets, curly braces and angle brackets are not valid array syntax here.",
  },
  {
    kind: "choice",
    id: "php-strlen",
    lang: "php",
    prompt: "What does this print?",
    code: ['<?php echo strlen("Hello"); ?>'],
    options: ["5", "4", "6", "Hello"],
    correct: 0,
    codeOptions: true,
    hint: "Count the letters.",
    explain: "strlen returns how many characters the string has: H, e, l, l, o is 5.",
  },
];
