import type { ChestQuestion } from "../types";

export const SQL_BANK: readonly ChestQuestion[] = [
  {
    kind: "blank",
    id: "sql-from",
    lang: "sql",
    prompt: "Read every name from the users table.",
    code: ["SELECT name ___ users;"],
    answers: ["FROM"],
    caseSensitive: false,
    live: { kind: "notLegal", tokens: ["FORM", "FRM"], label: "an SQL keyword" },
    blocks: ["FROM", "INTO", "FORM", "WHERE"],
    hint: "You select columns from a table.",
    explain: "SELECT … FROM table picks columns from that table.",
  },
  {
    kind: "choice",
    id: "sql-where",
    lang: "sql",
    prompt: "Which clause keeps only the rows where age is over 18?",
    options: ["WHERE age > 18", "ORDER BY age > 18", "FILTER age > 18", "LIMIT 18"],
    correct: 0,
    codeOptions: true,
    hint: "This clause filters rows by a condition.",
    explain: "WHERE filters rows; ORDER BY sorts them and LIMIT caps how many come back.",
  },
  {
    kind: "choice",
    id: "sql-max",
    lang: "sql",
    prompt: "The scores table's points column holds 7, 3 and 9. What does this return?",
    code: ["SELECT MAX(points) FROM scores;"],
    options: ["9", "3", "19", "7"],
    correct: 0,
    codeOptions: true,
    hint: "MAX picks one value.",
    explain: "MAX returns the largest value in the column: 9.",
  },
  {
    kind: "blank",
    id: "sql-order",
    lang: "sql",
    prompt: "List the users from the youngest to the oldest.",
    code: ["SELECT name FROM users ___ BY age;"],
    answers: ["ORDER"],
    caseSensitive: false,
    live: { kind: "notLegal", tokens: ["SORT", "ARRANGE", "ORDERED", "RANK"], label: "an SQL keyword" },
    blocks: ["ORDER", "GROUP", "SORT", "WHERE"],
    hint: "It is the clause that puts the rows in a sequence.",
    explain: "ORDER BY sorts the rows, smallest first unless you add DESC. GROUP BY collects rows into groups and WHERE filters them.",
  },
  {
    kind: "choice",
    id: "sql-count",
    lang: "sql",
    prompt: "The users table has 4 rows. What does this return?",
    code: ["SELECT COUNT(*) FROM users;"],
    options: ["4", "1", "*", "The names of the users"],
    correct: 0,
    codeOptions: true,
    hint: "COUNT answers 'how many?'.",
    explain: "COUNT(*) returns how many rows there are: 4, as one number.",
  },
  {
    kind: "choice",
    id: "sql-insert",
    lang: "sql",
    prompt: "Which statement adds a new row to the users table?",
    options: ["INSERT INTO users VALUES (5, 'Ana');", "ADD INTO users VALUES (5, 'Ana');", "UPDATE users VALUES (5, 'Ana');", "APPEND users VALUES (5, 'Ana');"],
    correct: 0,
    codeOptions: true,
    hint: "The statement's first word is the verb for putting something in.",
    explain: "INSERT INTO adds a row. UPDATE changes rows that already exist, and ADD and APPEND are not SQL statements for this.",
  },
];
